# Generated by Django 4.0.5 on 2022-07-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoes',
            name='copiou',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='imprimiu',
            field=models.BooleanField(default=False),
        ),
    ]
